import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header className="h-20 bg-sky-500">
        <h1>
          KM AIR SERVICES
        </h1>
      </header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {children}

      </body>
      <Footer />
    </html>
  );
}


const Footer = () => (<footer className="fixed w-full bottom-0">
  {/* <div className="pe-0 border"> */}
  <div className="text-right bg-amber-200 ">
    KM AIR SERVICE 2025(c)
  </div>
  {/* </div> */}
</footer>)